In [2]:
import numpy as np

In [3]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
np.ones(shape=(2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [5]:
type(0.)

float

In [6]:
type(1)

int

In [7]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [8]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [10]:
arr2 = np.random.randint(0,100,10)

In [11]:
arr2.mean()

40.7